name: Laravel

on:
  push:
    branches: [ main, development]
  pull_request:
    branches: [ main, development]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
#    - name: Create Database
#      run: |
#        mkdir -p database
#        touch database/database.sqlite
#    - name: Execute tests (Unit and Feature tests) via PHPUnit
#      env:
#        DB_CONNECTION: sqlite
#        DB_DATABASE: database/database.sqlite

    - name: Set up MySQL
#      env:
#        DB_TEST_DATABASE: test_db
#        DB_TEST_USERNAME: root
#        DB_TEST_PASSWORD: root
      run: |
            sudo /etc/init.d/mysql start
            mysql -e 'CREATE DATABASE ${{ env.DB_TEST_DATABASE }};' -u${{ env.DB_TEST_USERNAME }} -p${{ env.DB_TEST_PASSWORD }}
    - name: Execute tests
#      env:
#        DB_TEST_DATABASE: test_db
#        DB_TEST_USERNAME: root
#        DB_TEST_PASSWORD: root
      run: vendor/bin/phpunit
